/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ir_moke_ni_NativeLibrary */

#ifndef _Included_ir_moke_ni_NativeLibrary
#define _Included_ir_moke_ni_NativeLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ir_moke_ni_NativeLibrary
 * Method:    sum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_ir_moke_ni_jni_NativeLibrary_sum
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
